# Countries Draft3

In [71]:
import pandas as pd
import numpy as np
import sqlite3
import seaborn as sns
import matplotlib as mpl
import matplotlib.pyplot as plt
import warnings
import datetime
import matplotlib.dates as mdates

from scipy import stats
from matplotlib.dates import DateFormatter
from IPython.display import display

# Load Raw Data

In [72]:
db_survey = sqlite3.connect(
    "C:\\Users\\Space\\Documents\\py\\Projects\\TuringCollege\\TechMentalHealth\\DataSet\\mental_health.sqlite"
)

# Display Parameters

## Display Features

In [73]:
%matplotlib inline
pd.options.display.max_rows = 300000
pd.options.display.max_columns = 999
pd.options.display.max_colwidth = 500

## Colors

In [74]:
ord_color = "bisque"
spec_lev1 = "crimson"
spec_lev2 = "orangered"
spec_lev3 = "lightcoral"
male_color = "royalblue"
female_color = "pink"
graph_color1 = "indianred"
graph_color2 = "slategrey"

## Figure Parameters

In [75]:
size = 20

params = {
    "font.family": "Times New Roman",
    "font.size": size,
    "axes.labelsize": size,
    "xtick.labelsize": size * 0.75,
    "ytick.labelsize": size * 0.75,
    "figure.titlesize": size * 1.5,
    "axes.titlesize": size * 1.5,
    "axes.titlepad": size,
    "axes.labelpad": size - 10,
    "lines.linewidth": 2,
    "axes.spines.top": False,
    "axes.spines.right": False,
    "axes.spines.left": False,
    "axes.spines.bottom": False,
    "legend.fontsize": size,
}

# Answers

In [76]:
df_answers = pd.read_sql_query("SELECT * FROM Answer", db_survey)

# Participant Countries

In [86]:
df_Answer3 = pd.read_sql_query(
    "SELECT AnswerText FROM Answer where QuestionID = 3",
    db_survey
)
df_Answer3.head()

       AnswerText
0   United States
1   United States
2          Canada
3  United Kingdom
4   United States

In [88]:
Answer3_count = df_Answer3['AnswerText'].value_counts()
Answer3_count

United States of America    1853
United States                751
United Kingdom               482
Canada                       199
Germany                      136
Netherlands                   98
Australia                     73
France                        51
Ireland                       51
India                         50
Brazil                        37
Sweden                        29
Switzerland                   28
Spain                         26
New Zealand                   24
Portugal                      23
Poland                        21
Italy                         19
Belgium                       17
Russia                        16
South Africa                  16
Finland                       13
Bulgaria                      13
Norway                        12
Mexico                        12
Austria                       10
Japan                          9
Israel                         9
Denmark                        9
Romania                        9
Pakistan                       7
Greece                         7
Czech Republic                 6
Colombia                       6
Estonia                        5
Singapore                      5
Turkey                         5
Hungary                        4
Serbia                         4
Croatia                        4
Argentina                      4
Afghanistan                    3
Bangladesh                     3
Ukraine                        3
Chile                          3
Indonesia                      3
Bosnia and Herzegovina         3
Other                          2
Uruguay                        2
Slovakia                       2
-1                             2
Algeria                        2
Lithuania                      2
Iceland                        2
China                          2
Georgia                        2
Costa Rica                     2
Hong Kong                      2
Nigeria                        2
Latvia                         2
Mauritius                      1
Kenya                          1
Ethiopia                       1
Macedonia                      1
Belarus                        1
Jordan                         1
Saudi Arabia                   1
Zimbabwe                       1
Taiwan                         1
Guatemala                      1
Ecuador                        1
Iran                           1
Brunei                         1
Vietnam                        1
Venezuela                      1
Slovenia                       1
Philippines                    1
Moldova                        1
Bahamas, The                   1
Thailand                       1
Ghana                          1
Name: AnswerText, dtype: int64

In [90]:
df_Answer3_count = pd.DataFrame(Answer3_count)
df_Answer3_count

                          AnswerText
United States of America        1853
United States                    751
United Kingdom                   482
Canada                           199
Germany                          136
Netherlands                       98
Australia                         73
France                            51
Ireland                           51
India                             50
Brazil                            37
Sweden                            29
Switzerland                       28
Spain                             26
New Zealand                       24
Portugal                          23
Poland                            21
Italy                             19
Belgium                           17
Russia                            16
South Africa                      16
Finland                           13
Bulgaria                          13
Norway                            12
Mexico                            12
Austria                           10
Japan                              9
Israel                             9
Denmark                            9
Romania                            9
Pakistan                           7
Greece                             7
Czech Republic                     6
Colombia                           6
Estonia                            5
Singapore                          5
Turkey                             5
Hungary                            4
Serbia                             4
Croatia                            4
Argentina                          4
Afghanistan                        3
Bangladesh                         3
Ukraine                            3
Chile                              3
Indonesia                          3
Bosnia and Herzegovina             3
Other                              2
Uruguay                            2
Slovakia                           2
-1                                 2
Algeria                            2
Lithuania                          2
Iceland                            2
China                              2
Georgia                            2
Costa Rica                         2
Hong Kong                          2
Nigeria                            2
Latvia                             2
Mauritius                          1
Kenya                              1
Ethiopia                           1
Macedonia                          1
Belarus                            1
Jordan                             1
Saudi Arabia                       1
Zimbabwe                           1
Taiwan                             1
Guatemala                          1
Ecuador                            1
Iran                               1
Brunei                             1
Vietnam                            1
Venezuela                          1
Slovenia                           1
Philippines                        1
Moldova                            1
Bahamas, The                       1
Thailand                           1
Ghana                              1

In [91]:
df_Answer3_count = df_Answer3_count.reset_index()
df_Answer3_count

                       index  AnswerText
0   United States of America        1853
1              United States         751
2             United Kingdom         482
3                     Canada         199
4                    Germany         136
5                Netherlands          98
6                  Australia          73
7                     France          51
8                    Ireland          51
9                      India          50
10                    Brazil          37
11                    Sweden          29
12               Switzerland          28
13                     Spain          26
14               New Zealand          24
15                  Portugal          23
16                    Poland          21
17                     Italy          19
18                   Belgium          17
19                    Russia          16
20              South Africa          16
21                   Finland          13
22                  Bulgaria          13
23                    Norway          12
24                    Mexico          12
25                   Austria          10
26                     Japan           9
27                    Israel           9
28                   Denmark           9
29                   Romania           9
30                  Pakistan           7
31                    Greece           7
32            Czech Republic           6
33                  Colombia           6
34                   Estonia           5
35                 Singapore           5
36                    Turkey           5
37                   Hungary           4
38                    Serbia           4
39                   Croatia           4
40                 Argentina           4
41               Afghanistan           3
42                Bangladesh           3
43                   Ukraine           3
44                     Chile           3
45                 Indonesia           3
46    Bosnia and Herzegovina           3
47                     Other           2
48                   Uruguay           2
49                  Slovakia           2
50                        -1           2
51                   Algeria           2
52                 Lithuania           2
53                   Iceland           2
54                     China           2
55                   Georgia           2
56                Costa Rica           2
57                 Hong Kong           2
58                   Nigeria           2
59                    Latvia           2
60                 Mauritius           1
61                     Kenya           1
62                  Ethiopia           1
63                 Macedonia           1
64                   Belarus           1
65                    Jordan           1
66              Saudi Arabia           1
67                  Zimbabwe           1
68                    Taiwan           1
69                 Guatemala           1
70                   Ecuador           1
71                      Iran           1
72                    Brunei           1
73                   Vietnam           1
74                 Venezuela           1
75                  Slovenia           1
76               Philippines           1
77                   Moldova           1
78              Bahamas, The           1
79                  Thailand           1
80                     Ghana           1

In [93]:
df_Answer3_count = df_Answer3_count.rename(
    columns={"index": "Country", "AnswerText": "Count"}
)
df_Answer3_count

                     Country  Count
0   United States of America   1853
1              United States    751
2             United Kingdom    482
3                     Canada    199
4                    Germany    136
5                Netherlands     98
6                  Australia     73
7                     France     51
8                    Ireland     51
9                      India     50
10                    Brazil     37
11                    Sweden     29
12               Switzerland     28
13                     Spain     26
14               New Zealand     24
15                  Portugal     23
16                    Poland     21
17                     Italy     19
18                   Belgium     17
19                    Russia     16
20              South Africa     16
21                   Finland     13
22                  Bulgaria     13
23                    Norway     12
24                    Mexico     12
25                   Austria     10
26                     Japan      9
27                    Israel      9
28                   Denmark      9
29                   Romania      9
30                  Pakistan      7
31                    Greece      7
32            Czech Republic      6
33                  Colombia      6
34                   Estonia      5
35                 Singapore      5
36                    Turkey      5
37                   Hungary      4
38                    Serbia      4
39                   Croatia      4
40                 Argentina      4
41               Afghanistan      3
42                Bangladesh      3
43                   Ukraine      3
44                     Chile      3
45                 Indonesia      3
46    Bosnia and Herzegovina      3
47                     Other      2
48                   Uruguay      2
49                  Slovakia      2
50                        -1      2
51                   Algeria      2
52                 Lithuania      2
53                   Iceland      2
54                     China      2
55                   Georgia      2
56                Costa Rica      2
57                 Hong Kong      2
58                   Nigeria      2
59                    Latvia      2
60                 Mauritius      1
61                     Kenya      1
62                  Ethiopia      1
63                 Macedonia      1
64                   Belarus      1
65                    Jordan      1
66              Saudi Arabia      1
67                  Zimbabwe      1
68                    Taiwan      1
69                 Guatemala      1
70                   Ecuador      1
71                      Iran      1
72                    Brunei      1
73                   Vietnam      1
74                 Venezuela      1
75                  Slovenia      1
76               Philippines      1
77                   Moldova      1
78              Bahamas, The      1
79                  Thailand      1
80                     Ghana      1

In [95]:
df_Answer3_count["Country"] = df_Answer3_count["Country"].replace(
    {
        "-1": "Other",
        "Bahamas, The": "Bahamas",
        "United States of America": 'United States'
    }
)
df_Answer3_count

                   Country  Count
0            United States   1853
1            United States    751
2           United Kingdom    482
3                   Canada    199
4                  Germany    136
5              Netherlands     98
6                Australia     73
7                   France     51
8                  Ireland     51
9                    India     50
10                  Brazil     37
11                  Sweden     29
12             Switzerland     28
13                   Spain     26
14             New Zealand     24
15                Portugal     23
16                  Poland     21
17                   Italy     19
18                 Belgium     17
19                  Russia     16
20            South Africa     16
21                 Finland     13
22                Bulgaria     13
23                  Norway     12
24                  Mexico     12
25                 Austria     10
26                   Japan      9
27                  Israel      9
28                 Denmark      9
29                 Romania      9
30                Pakistan      7
31                  Greece      7
32          Czech Republic      6
33                Colombia      6
34                 Estonia      5
35               Singapore      5
36                  Turkey      5
37                 Hungary      4
38                  Serbia      4
39                 Croatia      4
40               Argentina      4
41             Afghanistan      3
42              Bangladesh      3
43                 Ukraine      3
44                   Chile      3
45               Indonesia      3
46  Bosnia and Herzegovina      3
47                   Other      2
48                 Uruguay      2
49                Slovakia      2
50                   Other      2
51                 Algeria      2
52               Lithuania      2
53                 Iceland      2
54                   China      2
55                 Georgia      2
56              Costa Rica      2
57               Hong Kong      2
58                 Nigeria      2
59                  Latvia      2
60               Mauritius      1
61                   Kenya      1
62                Ethiopia      1
63               Macedonia      1
64                 Belarus      1
65                  Jordan      1
66            Saudi Arabia      1
67                Zimbabwe      1
68                  Taiwan      1
69               Guatemala      1
70                 Ecuador      1
71                    Iran      1
72                  Brunei      1
73                 Vietnam      1
74               Venezuela      1
75                Slovenia      1
76             Philippines      1
77                 Moldova      1
78                 Bahamas      1
79                Thailand      1
80                   Ghana      1

In [97]:
Answer3_count = df_Answer3_count['Country'].value_counts()
Answer3_count

United States             2
Other                     2
Lithuania                 1
Latvia                    1
Nigeria                   1
Hong Kong                 1
Costa Rica                1
Georgia                   1
China                     1
Iceland                   1
Algeria                   1
Kenya                     1
Slovakia                  1
Uruguay                   1
Bosnia and Herzegovina    1
Indonesia                 1
Chile                     1
Ukraine                   1
Mauritius                 1
Ethiopia                  1
Afghanistan               1
Brunei                    1
Thailand                  1
Bahamas                   1
Moldova                   1
Philippines               1
Slovenia                  1
Venezuela                 1
Vietnam                   1
Iran                      1
Macedonia                 1
Ecuador                   1
Guatemala                 1
Taiwan                    1
Zimbabwe                  1
Saudi Arabia              1
Jordan                    1
Belarus                   1
Bangladesh                1
Argentina                 1
United Kingdom            1
Sweden                    1
Belgium                   1
Italy                     1
Poland                    1
Portugal                  1
New Zealand               1
Spain                     1
Switzerland               1
Brazil                    1
South Africa              1
India                     1
Ireland                   1
France                    1
Australia                 1
Netherlands               1
Germany                   1
Canada                    1
Russia                    1
Finland                   1
Croatia                   1
Greece                    1
Serbia                    1
Hungary                   1
Turkey                    1
Singapore                 1
Estonia                   1
Colombia                  1
Czech Republic            1
Pakistan                  1
Bulgaria                  1
Romania                   1
Denmark                   1
Israel                    1
Japan                     1
Austria                   1
Mexico                    1
Norway                    1
Ghana                     1
Name: Country, dtype: int64